### ISSUE TITLE
Flere unicode-feilmeldinger fra validatoren

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aksel-website#16]
Validatoren har noen issues med unicode karakterer i font-urlene i head:

![image](https://user-images.githubusercontent.com/91880567/140314738-03243a61-c310-46dd-8322-49717e35fdaf.png)

**Comment by sarahbrodwall** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ny nettside: Luke ut UU-feil og mangler](https://trello.com/c/i3P6bWn6/46-ny-nettside-luke-ut-uu-feil-og-mangler)

**Comment by KenAJoh** [comment]
Gjelder dette for design.nav.no eller https://verktoykassen.vercel.app/ ?

**Comment by sarahbrodwall** [comment]
Det er https://verktoykassen.vercel.app/:  https://validator.w3.org/nu/?doc=https%3A%2F%2Fverktoykassen.vercel.app%2F

**Comment by KenAJoh** [comment]
Ser ut som disse validerings-feilene ikke gjelder lengre (men har noen andre som må fikses) så lukker denne
