### ISSUE TITLE
Gjør det mulig å lenke til epost-adresser

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aksel-website#55]
![image](https://user-images.githubusercontent.com/91880567/156363645-aa2cef8a-3790-4fb8-af81-f05005d971cc.png)

Fint om vi kan lenke til mailto:url'er.

**Comment by sarahbrodwall** [comment]
![image](https://user-images.githubusercontent.com/91880567/179483815-c2384d93-69c3-436b-af39-fad921c10d4c.png)
 Denne fra https://aksel.nav.no/artikkel/kurs?tema=universell-utforming

**Comment by KenAJoh** [comment]
Lenke knappen støtter nå mailto: protokollen 🚀  
![Screenshot 2022-08-17 at 07 45 01](https://user-images.githubusercontent.com/26967723/185043643-c8aedc1b-0652-45e4-bb6a-becf5e5f50b2.png)
