### ISSUE TITLE
Linjehøyden er under minimumsverdien

### ISSUE THREAD

**Issue by eilifjohansen** [navikt/aksel-website#56]
Siteimprove har oppdaget et brudd med tanke på UU, dette angår “Linjehøyden er under minimumsverdien” Siteimprove sitt forslag til endring her er “Sett line-height til minst 1.5.“.  Å fikse dette kan gjøre det enklere å lese siden for brukerene.

[Forsiden Aksel Siteimprove Rapport](https://my2.siteimprove.com/Inspector/1005799/A11Y/Page?PageId=25932307714&impmd=8258C0C0E52E71B418EF4A5027E513FA#/)

**Comment by KenAJoh** [comment]
Dette er noe som er bygd inn i typo-komponentene våre, så får ikke gjort så mye med det på selve nettsiden. Men vil se mer på det for komponentene etterhvert
