### ISSUE TITLE
Gjør det mulig å skrive med en løsere struktur

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aksel-website#66]
Jeg opplever prosessen av å skrive i Sanity som svært tung.  Jeg skjønner at formålet med strukturen som det er nå er å øke consistency, men jeg opplever at alle nivåene gjør det vanskelig å få en oversikt over det jeg skriver og finne frem til informasjon når jeg redigerer en artikkel.  Er det mulig å tilby en artikkelmal som er løsere?

**Comment by macbruker** [comment]
### Støtter dette 200% 🙏 

Mitt drømmeoppsett i Sanity Studio er riktekst-editor som default, med mulighet til sette inn blokker der vi har behov for mer spesialisert innhold. Noen blokker er kanskje hensiktsmessig å bare gjøre tilgjengelige i dokumentasjonen, mens andre kan være nyttige uansett hvilken side vi jobber med innhold på.

Om vi sliter med kvaliteten eller oppsettet på enkelte sider, synes jeg vi skal prøve å fikse det uten å legge til mer teknologi. Sjekklister og gjennomlesing fra kollegaer pleier å fungere veldig bra.

**Comment by KenAJoh** [comment]
Dette er nå fikset! Er nå bare et stort riktekstfelt.
<img width="644" alt="Screenshot 2022-07-15 at 17 38 04" src="https://user-images.githubusercontent.com/26967723/179257808-8d11bf95-6be6-4279-bc16-9a39aa7eae9f.png">
