### ISSUE TITLE
Tooltip-docs: Eksempelknappen mangler tekst

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aksel-website#70]
Gi knappen tilgjengelig tekst, selv om det er bare en demo--folk ser på koden så den bør være i orden.  Bruk gjerne aria-labelledby + title-teknikken til SVGen og fjern aria-hidden.  Tekst kan gjerne være "print" eller "demo knapp".

**Comment by KenAJoh** [comment]
Fikset nå 🚀
