### ISSUE TITLE
highlightet tekst er uleselig i redaktørgrensesnittet

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aksel-website#73]
Ser slik ut: 
![image](https://user-images.githubusercontent.com/91880567/179482691-a4cc79b0-4a41-4ad2-833e-c3ce3e391422.png)

**Comment by KenAJoh** [comment]
Er dette bare vanlig highlighting inne i et felt i sanity? 

Ser slik ut hos meg, så lurer på om dette er maskin/nettleser-spesifikt 🤔 
<img width="634" alt="Screenshot 2022-07-18 at 13 01 13" src="https://user-images.githubusercontent.com/26967723/179498139-419f97fb-7568-4555-b13f-1b49765cfe11.png">

**Comment by sarahbrodwall** [comment]
Jeg klarer heller ikke gjenskape det nå.  Åpner det opp igjen om jeg finner ut av det.
