### ISSUE TITLE
Gjør det mulig å bruke riktekst i figcaptions

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aksel-website#76]
Jeg ønsker å bruke et bilde der jeg blir nødt til å lenke til en kilde.  Hadde vært fint med mulighet til å gjøre dette direkte i figcaption.

**Comment by KenAJoh** [comment]
Tenker jeg kanskje lager et eget felt for kilde og kilde-lenke. Noe lignende eks NRK 

Eks
<img width="748" alt="Screenshot 2022-07-18 at 12 53 24" src="https://user-images.githubusercontent.com/26967723/179496956-26d77678-02a4-40fc-9160-ef92b3eb4cbe.png">

NRK
<img width="692" alt="Screenshot 2022-07-18 at 12 53 32" src="https://user-images.githubusercontent.com/26967723/179496938-3aca2c4f-6a96-4079-a965-29b712b8db51.png">

**Comment by KenAJoh** [comment]
Kan nå legger til kilder med tekst + lenker under bilder 
![Screenshot 2022-08-17 at 08 17 49](https://user-images.githubusercontent.com/26967723/185048279-ea56b260-9d1b-4e1e-afef-ebb0fb97be77.png)
![Screenshot 2022-08-17 at 08 17 39](https://user-images.githubusercontent.com/26967723/185048282-fe18d55e-56eb-411c-8d68-f9cdfd18b1a6.png)
