### ISSUE TITLE
Legg til IDer på headingene 

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aksel-website#78]
Da kan vi lenke direkte til seksjoner i andre artikler.

**Comment by KenAJoh** [comment]
URL oppdateres nå dynamiskt ettersom man scroller ned på siden 
![Screenshot 2022-08-15 at 08 52 45](https://user-images.githubusercontent.com/26967723/184589622-cf7d2ee1-4d82-40ae-8dc7-39a7de93bdb6.png)
![Screenshot 2022-08-15 at 08 52 40](https://user-images.githubusercontent.com/26967723/184589628-f5d65906-b557-48c2-a084-19dc7988523b.png)

Kan da kopiere denne og linke til riktig heading. Vi hadde tidligere en "kopier lenke til heading"-knapp på alle h2-headings, men ble ikke brukt så jeg fjernet den.
