### ISSUE TITLE
Innholdsfortegnelse for lange artikler

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aksel-website#81]
Det hadde vært fint om Aksel-artiklene kunne ha en innholdsfortegnelse over innhold på siden.  Noen av artiklene er veldig lange og blir veldig uoversiktlig.  Trodde vi hadde denne før?

**Comment by KenAJoh** [comment]
Lukker denne da artikler nå har dette (blogg får det kanskje etterhvert)
