### ISSUE TITLE
"Under arbeid" med mulighet til å vise innhold

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/aksel-website#83]
Noen ganger hadde det vært praktisk å kunne vise artikkelens innhold på samme tid som vi har en "Under arbeid" banner.  Er det mulig å få en option til å vise innholdet når en artikkel er under arbeid?

**Comment by KenAJoh** [comment]
Er lagt til mulighet til det nå i Sanity 🚀  
![Screenshot 2022-08-15 at 08 23 11](https://user-images.githubusercontent.com/26967723/184586568-b38ca7be-13e6-4828-9259-1469bf0365cf.png)
